### ISSUE TITLE
Muddy pet does nothing

### ISSUE THREAD

**Issue by RuthAnn1** [Techwise-Team-15/my_pet#102]
## Feature Request

**Description:**
When the pet is muddy the player cannot do anything with the pet except give the pet a bath.  While the pet is muddy it will have a thought bubble of the watering can.  That way the player knows what the pet needs to become happier.  Also when the pet is dirty happiness decreases faster.

**Motivation:**
This will keep the sprites from going from dirty to clean instantly and the player will learn how to keep the pet happy.

**Current Behavior:**
Currently the player can still interact with the muddy pet.

**Proposed Solution:**
N/N

**Code Snippet:**
N/A

**Additional Information:**
N/A

**Comment by Donnyd88** [comment]
Pet Rock will now do nothing but interact with the watering can.
