### ISSUE TITLE
Pet Sound Effects

### ISSUE THREAD

**Issue by dinaolmelak** [Techwise-Team-15/my_pet#58]
## Feature Request

**Description:**
Sound Effects are an essential part of any game. This ticket is going to focus on the sound effects for the pets. 

**Motivation:**
Motivated by the foundation of the game.

**Current Behavior:**
There are no sound effects currently.

**Proposed Solution:**
Get sound effects. 🤔 Also check on licensing or any restrictions there might be before getting them. 

**Code Snippet:**
N/A

**Additional Information:**
N/A

**Comment by RuthAnn1** [comment]
I can pull sound from videos I record to create sound effects for the game.  This would be the best way to endure that there will not be any licensing issues.
