### ISSUE TITLE
Pet misbehaving

### ISSUE THREAD

**Issue by RuthAnn1** [Techwise-Team-15/my_pet#75]
## Feature Request

**Description:**
This feature will cause the pet to misbehave if not interacted with.  After a set amount of seconds the pet will jump and hit the table then land in the mud puddle.  When the table is hit by the rock it will trigger the animation of the vase falling off the table and breaking.

**Motivation:**
To make the game interactive and the player feel as if they are caring for a pet, the pet must misbehave.  This will give the player a lot more to think about when playing the game.

**Current Behavior:**
Currently the game does not have the pet misbehaving.

**Proposed Solution:**
N/A

**Code Snippet:**
N/A

**Additional Information:**
It would be interesting to have the happiness bar go down each time the pet misbehaves.  This ticket needs to wait till ticket number #68 is completed.  Be sure to watch for that tickets completion.

**Comment by dinaolmelak** [comment]
![Image](https://github.com/Techwise-Team-15/my_pet/assets/32272045/5c48b452-8e40-4124-b608-a10fd29b4ba4)
