### ISSUE TITLE
Bars

### ISSUE THREAD

**Issue by dinaolmelak** [Techwise-Team-15/my_pet#8]
We would need health, happiness, food, and a thirst bar to indicate to the player. Because if one of these bars goes to 0% pet dies or leaves or has different side effects.

**Comment by Donnyd88** [comment]
2603120ce825c89eac88211de6d6043af80cb2b2 Just realized happiness was listed here too. I can add that as well, but the rest of the bars are there.

**Comment by Donnyd88** [comment]
c422c12f8269298ec8cfe8d2352f0cbdaa154540
