### ISSUE TITLE
Pet getting dirty over time

### ISSUE THREAD

**Issue by RuthAnn1** [Techwise-Team-15/my_pet#80]
## Feature Request

**Description:**
This feature will allow the pet to start to get dirty as the game goes on.  Not just when the pet jumps into the mud puddle.  When the pet is dirty the happiness goes down and the pet will need a bath.

**Motivation:**
The feature will make the pet seem more realistic to the player and will keep them interested in the game longer.

**Current Behavior:**
The game currently does not have this function.

**Proposed Solution:**
N/A

**Code Snippet:**
N/A

**Additional Information:**
This ticket can not be complete till ticket number #68 is finished. Please watch for the completion of that ticket.

**Comment by VanessaMedinaUNR** [comment]
Ticket is on hold until animations are provided. @Techwise-Team-15/everyone 
Cannot be done yet, due to missing animations for the rock being dirty while eating, drinking and playing.

**Comment by RuthAnn1** [comment]
@VanessaMedinaUNR  We have a ticket that will make it where the rock will not do the tasks when it is dirty.   The player needs to clean the rock with the watering can before it will eat, drink, play and sleep.

**Comment by VanessaMedinaUNR** [comment]
@RuthAnn1 
Thank you for you input. Ticket will resume.

**Comment by dinaolmelak** [comment]
@RuthAnn1 so when would that ticket for other activities being inactive be turned on?, is it when the rock gets slightly dirty or after it misbehaves? Cause it currently misbehaves after 10 seconds

**Comment by VanessaMedinaUNR** [comment]
Donald helped me finish it up today. Created a pull request and waiting upon review.
