### ISSUE TITLE
Sleeping Rock Pauses Bars

### ISSUE THREAD

**Issue by RuthAnn1** [Techwise-Team-15/my_pet#95]
## Feature Request

**Description:**
When the Rock is is put to bed the bars get paused until the pet rock wakes up.  When the rock is awake then the bars move again. The pet should sleep for 20 seconds.  Once awake the pet goes back to the center in idle position.

**Motivation:**
This is an important addition to the game because when the pets happiness goes down the player needs to be able to pause the bars.

**Current Behavior:**
Currently the pet will not pause the bars.

**Proposed Solution:**
N/A

**Code Snippet:**
N/A

**Additional Information:**
N/A

**Comment by dinaolmelak** [comment]
I realized that pausing the bars when the pet is also sleeping means that I will have to `set sleep timer first`
